name: ShadowcraftRelics
version: '${project.version}'
main: world.sc2.shadowcraftrelics.ShadowcraftRelics
api-version: '1.19'
commands:
  giverelictag:
    description: Gives the player's held item the tag specific to a given Relic
    usage: /giverelictag <relic_name>
    permission: shadowcraftrelics.giverelictag

permissions:
  shadowcraftrelics.giverelictag:
    description: Gives the player the ability to use the /giverelictag command
    default: op